runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - name: Execute
    run: ./deploy/task-setup.sh
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}