name: deploy

on:
  push:

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: ./deploy/task-setup.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  run:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: ./deploy/task-run.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cleanup:
    needs: [setup, run]
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: ./deploy/task-cleanup.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  