name: deploy

on:
  push:

jobs:

  setup:
    uses: ./.github/jobs/setup.yml

  run:
    uses: ./.github/jobs/run.yml
    needs: [setup]

  cleanup:
    uses: ./.github/jobs/cleanup.yml
    needs: [setup, run]
  